name: food_delivery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: 2.0.2
  shrink_sidemenu: 2.0.0+2-null-safety
  bottom_navy_bar: 6.0.0
  flutter_slidable: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/img/
    - assets/icon/
  fonts: 
    - family: SF-Pro
      fonts: 
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
  uses-material-design: true

